### ISSUE TITLE
installSplitPackage problems

### ISSUE THREAD

**Issue by hemisphire** [solrudev/SimpleInstaller#10]
I suspect this is more due to my inexperience with Kotlin with your code, but I've been able to get installPackage() to work, but not installSplitPackage(). I'm trying to take an array of File and convert them to an array of ApkSource, but even after I do that, I get a compiler error of:  `Type mismatch: inferred type is () -> Unit but SessionOptions was expected` (located before the brace on the installSplitPackage() call).

```
val arr = mutableListOf<File>()
for (packageApk in packageApks) {
    val apkFile = FileUtils.getFile(packageApk)
    arr.add(apkFile)
}
var apks : Array<File> = arr.toTypedArray()
var apkSourceArray : Array<ApkSource> = apks.toApkSourceArray()

val result = PackageInstaller.installSplitPackage(*apkSourceArray) {
    notification {
        icon = R.drawable.ic_installer
    }
}
when (result) {
    is InstallResult.Success -> Log.i(TAG, getString(R.string.installed_successfully))
    is InstallResult.Failure -> {
        Log.i(TAG, result.toString())
        Log.i(TAG, getString(R.string.install_failed))
    }
}


```

**Comment by solrudev** [comment]
Add this import:
`import io.github.solrudev.simpleinstaller.installSplitPackage`

By the way, there's a convenient extension function overload which accepts `File` array, so you don't have to convert it to `ApkSource` array explicitly.

**Comment by hemisphire** [comment]
D'oh! You are correct on both accounts - it's working now. Thanks for the useful library and the fast response.
