### ISSUE TITLE
1st install works fine, subsequent installs fail

### ISSUE THREAD

**Issue by hemisphire** [solrudev/SimpleInstaller#11]
[Installer.zip](https://github.com/solrudev/SimpleInstaller/files/11519967/Installer.zip)

I've attached an app that uses the file picker to pick apks from the Download directory. It recreates a problem that I'm having, namely that the first time I run installPackage() it works fine, and then fails to finish when run again. I've tried with both ConfirmationStrategy.DEFERRED and ConfirmationStrategy.IMMEDIATE. I have used the simpleinstaller app and that works, so I would appreciate any insights as to why my code doesn't.

**Comment by solrudev** [comment]
It was a bug in the library. Fixed in af8a36399774c9789494327813ad1b6f114eaf4b.
Fix released in [4.2.3.](https://github.com/solrudev/SimpleInstaller/releases/tag/4.2.3)
Let me know if using this version resolved your issue.

**Comment by hemisphire** [comment]
Yes, it works correctly now. Thanks!
